/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.travels;

/**
 *
 * @author musialantoni
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_Container = new javax.swing.JPanel();
        jP_TopBar = new javax.swing.JPanel();
        jL_Exit = new javax.swing.JLabel();
        jL_Minimize = new javax.swing.JLabel();
        jL_NameOfAplicationFirstPart = new javax.swing.JLabel();
        jL_NameOfAplicationSecondPart = new javax.swing.JLabel();
        jP_Contents = new javax.swing.JPanel();
        jP_Accommodation = new javax.swing.JPanel();
        jL_Accommodation = new javax.swing.JLabel();
        jS_Accommodation = new javax.swing.JSeparator();
        jTF_1SearchAccommodation = new javax.swing.JTextField();
        jTF_2SearchAccommodation = new javax.swing.JTextField();
        jTF_3SearchAccommodation = new javax.swing.JTextField();
        jTF_4SearchAccommodation = new javax.swing.JTextField();
        jTF_5SearchAccommodation = new javax.swing.JTextField();
        jP_BookingOptions = new javax.swing.JPanel();
        jL_BookingOptions = new javax.swing.JLabel();
        jS_BookingOptions = new javax.swing.JSeparator();
        jTF_1SearchBookingOptions = new javax.swing.JTextField();
        jTF_2SearchBookingOptions = new javax.swing.JTextField();
        jTF_3SearchBookingOptions = new javax.swing.JTextField();
        jTF_4SearchBookingOptions = new javax.swing.JTextField();
        jTF_5SearchBookingOptions = new javax.swing.JTextField();
        jTF_6SearchBookingOptions = new javax.swing.JTextField();
        jTF_7SearchBookingOptions = new javax.swing.JTextField();
        jP_ListOfAttractions = new javax.swing.JPanel();
        jL_ListOfAttractions = new javax.swing.JLabel();
        jS_ListOfAttractions = new javax.swing.JSeparator();
        jTF_1SearchListOfAttractions = new javax.swing.JTextField();
        jTF_2SearchListOfAttractions = new javax.swing.JTextField();
        jTF_3SearchListOfAttractions = new javax.swing.JTextField();
        jTF_4SearchListOfAttractions = new javax.swing.JTextField();
        jTF_5SearchListOfAttractions = new javax.swing.JTextField();
        jTF_6SearchListOfAttractions = new javax.swing.JTextField();
        jTF_7SearchListOfAttractions = new javax.swing.JTextField();
        jTF_8SearchListOfAttractions = new javax.swing.JTextField();
        jTF_9SearchListOfAttractions = new javax.swing.JTextField();
        jP_Reserved = new javax.swing.JPanel();
        jL_Reserved = new javax.swing.JLabel();
        jS_Reserved = new javax.swing.JSeparator();
        jTF_1SearchReserved = new javax.swing.JTextField();
        jTF_2SearchReserved = new javax.swing.JTextField();
        jTF_3SearchReserved = new javax.swing.JTextField();
        jTF_4SearchReserved = new javax.swing.JTextField();
        jP_Buttons = new javax.swing.JPanel();
        jP_Load = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jP_Save = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jL_Line = new javax.swing.JLabel();
        jP_JourneyPlan = new javax.swing.JPanel();
        jSP_JourneyPlan = new javax.swing.JScrollPane();
        jTA_JourneyPlan = new javax.swing.JTextArea();
        jL_JourneyPlan = new javax.swing.JLabel();
        jS_JourneyPlan = new javax.swing.JSeparator();
        jTF_Search = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setName("MainPage"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jP_Container.setMaximumSize(new java.awt.Dimension(800, 600));
        jP_Container.setName("Container"); // NOI18N

        jP_TopBar.setBackground(new java.awt.Color(74, 78, 77));

        jL_Exit.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        jL_Exit.setForeground(java.awt.Color.white);
        jL_Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Exit.setText("x");

        jL_Minimize.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        jL_Minimize.setForeground(java.awt.Color.white);
        jL_Minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Minimize.setText("_");

        jL_NameOfAplicationFirstPart.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jL_NameOfAplicationFirstPart.setForeground(new java.awt.Color(0, 255, 0));
        jL_NameOfAplicationFirstPart.setText("Trip");

        jL_NameOfAplicationSecondPart.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jL_NameOfAplicationSecondPart.setForeground(new java.awt.Color(166, 84, 2));
        jL_NameOfAplicationSecondPart.setText("Mate");

        javax.swing.GroupLayout jP_TopBarLayout = new javax.swing.GroupLayout(jP_TopBar);
        jP_TopBar.setLayout(jP_TopBarLayout);
        jP_TopBarLayout.setHorizontalGroup(
            jP_TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_TopBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jL_NameOfAplicationFirstPart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_NameOfAplicationSecondPart)
                .addGap(317, 317, 317)
                .addComponent(jL_Minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jP_TopBarLayout.setVerticalGroup(
            jP_TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jL_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_Minimize, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addComponent(jL_NameOfAplicationFirstPart)
                .addComponent(jL_NameOfAplicationSecondPart))
        );

        jP_Contents.setBackground(new java.awt.Color(255, 255, 255));

        jP_Accommodation.setBackground(new java.awt.Color(255, 255, 255));
        jP_Accommodation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 78, 77)));
        jP_Accommodation.setMaximumSize(new java.awt.Dimension(202, 237));

        jL_Accommodation.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jL_Accommodation.setForeground(new java.awt.Color(74, 78, 77));
        jL_Accommodation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Accommodation.setText("Accommodation");

        jS_Accommodation.setBackground(new java.awt.Color(74, 78, 77));
        jS_Accommodation.setForeground(new java.awt.Color(74, 78, 77));

        jTF_1SearchAccommodation.setEditable(false);
        jTF_1SearchAccommodation.setBackground(new java.awt.Color(255, 255, 255));
        jTF_1SearchAccommodation.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_1SearchAccommodation.setForeground(new java.awt.Color(74, 78, 77));
        jTF_1SearchAccommodation.setText(" Not Found... :(");
        jTF_1SearchAccommodation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 78, 77)));
        jTF_1SearchAccommodation.setMaximumSize(new java.awt.Dimension(64, 25));
        jTF_1SearchAccommodation.setMinimumSize(new java.awt.Dimension(64, 25));
        jTF_1SearchAccommodation.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_2SearchAccommodation.setEditable(false);
        jTF_2SearchAccommodation.setBackground(new java.awt.Color(255, 255, 255));
        jTF_2SearchAccommodation.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_2SearchAccommodation.setBorder(null);
        jTF_2SearchAccommodation.setMaximumSize(new java.awt.Dimension(64, 25));
        jTF_2SearchAccommodation.setMinimumSize(new java.awt.Dimension(64, 25));
        jTF_2SearchAccommodation.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_3SearchAccommodation.setEditable(false);
        jTF_3SearchAccommodation.setBackground(new java.awt.Color(255, 255, 255));
        jTF_3SearchAccommodation.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_3SearchAccommodation.setForeground(new java.awt.Color(74, 78, 77));
        jTF_3SearchAccommodation.setBorder(null);
        jTF_3SearchAccommodation.setMaximumSize(new java.awt.Dimension(64, 25));
        jTF_3SearchAccommodation.setMinimumSize(new java.awt.Dimension(64, 25));
        jTF_3SearchAccommodation.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_4SearchAccommodation.setEditable(false);
        jTF_4SearchAccommodation.setBackground(new java.awt.Color(255, 255, 255));
        jTF_4SearchAccommodation.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_4SearchAccommodation.setForeground(new java.awt.Color(74, 78, 77));
        jTF_4SearchAccommodation.setBorder(null);
        jTF_4SearchAccommodation.setMaximumSize(new java.awt.Dimension(64, 25));
        jTF_4SearchAccommodation.setMinimumSize(new java.awt.Dimension(64, 25));
        jTF_4SearchAccommodation.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_5SearchAccommodation.setEditable(false);
        jTF_5SearchAccommodation.setBackground(new java.awt.Color(255, 255, 255));
        jTF_5SearchAccommodation.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_5SearchAccommodation.setForeground(new java.awt.Color(74, 78, 77));
        jTF_5SearchAccommodation.setBorder(null);
        jTF_5SearchAccommodation.setMaximumSize(new java.awt.Dimension(64, 25));
        jTF_5SearchAccommodation.setMinimumSize(new java.awt.Dimension(64, 25));
        jTF_5SearchAccommodation.setPreferredSize(new java.awt.Dimension(64, 25));

        javax.swing.GroupLayout jP_AccommodationLayout = new javax.swing.GroupLayout(jP_Accommodation);
        jP_Accommodation.setLayout(jP_AccommodationLayout);
        jP_AccommodationLayout.setHorizontalGroup(
            jP_AccommodationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_AccommodationLayout.createSequentialGroup()
                .addGroup(jP_AccommodationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_AccommodationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jL_Accommodation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_AccommodationLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jS_Accommodation, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jP_AccommodationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_1SearchAccommodation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_AccommodationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_2SearchAccommodation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_AccommodationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_3SearchAccommodation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_AccommodationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_4SearchAccommodation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_AccommodationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_5SearchAccommodation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jP_AccommodationLayout.setVerticalGroup(
            jP_AccommodationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_AccommodationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_Accommodation)
                .addGap(3, 3, 3)
                .addComponent(jS_Accommodation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTF_1SearchAccommodation, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_2SearchAccommodation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_3SearchAccommodation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_4SearchAccommodation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_5SearchAccommodation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jP_BookingOptions.setBackground(new java.awt.Color(255, 255, 255));
        jP_BookingOptions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 78, 77)));
        jP_BookingOptions.setMaximumSize(new java.awt.Dimension(202, 302));

        jL_BookingOptions.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jL_BookingOptions.setForeground(new java.awt.Color(74, 78, 77));
        jL_BookingOptions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_BookingOptions.setText("Booking Options");

        jS_BookingOptions.setForeground(new java.awt.Color(74, 78, 77));

        jTF_1SearchBookingOptions.setEditable(false);
        jTF_1SearchBookingOptions.setBackground(new java.awt.Color(255, 255, 255));
        jTF_1SearchBookingOptions.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_1SearchBookingOptions.setForeground(new java.awt.Color(74, 78, 77));
        jTF_1SearchBookingOptions.setBorder(null);
        jTF_1SearchBookingOptions.setMinimumSize(null);
        jTF_1SearchBookingOptions.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_2SearchBookingOptions.setEditable(false);
        jTF_2SearchBookingOptions.setBackground(new java.awt.Color(255, 255, 255));
        jTF_2SearchBookingOptions.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_2SearchBookingOptions.setForeground(new java.awt.Color(74, 78, 77));
        jTF_2SearchBookingOptions.setBorder(null);
        jTF_2SearchBookingOptions.setMinimumSize(null);
        jTF_2SearchBookingOptions.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_3SearchBookingOptions.setEditable(false);
        jTF_3SearchBookingOptions.setBackground(new java.awt.Color(255, 255, 255));
        jTF_3SearchBookingOptions.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_3SearchBookingOptions.setForeground(new java.awt.Color(74, 78, 77));
        jTF_3SearchBookingOptions.setBorder(null);
        jTF_3SearchBookingOptions.setMinimumSize(null);
        jTF_3SearchBookingOptions.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_4SearchBookingOptions.setEditable(false);
        jTF_4SearchBookingOptions.setBackground(new java.awt.Color(255, 255, 255));
        jTF_4SearchBookingOptions.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_4SearchBookingOptions.setForeground(new java.awt.Color(74, 78, 77));
        jTF_4SearchBookingOptions.setBorder(null);
        jTF_4SearchBookingOptions.setMinimumSize(null);
        jTF_4SearchBookingOptions.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_5SearchBookingOptions.setEditable(false);
        jTF_5SearchBookingOptions.setBackground(new java.awt.Color(255, 255, 255));
        jTF_5SearchBookingOptions.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_5SearchBookingOptions.setForeground(new java.awt.Color(74, 78, 77));
        jTF_5SearchBookingOptions.setBorder(null);
        jTF_5SearchBookingOptions.setMinimumSize(null);
        jTF_5SearchBookingOptions.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_6SearchBookingOptions.setEditable(false);
        jTF_6SearchBookingOptions.setBackground(new java.awt.Color(255, 255, 255));
        jTF_6SearchBookingOptions.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_6SearchBookingOptions.setForeground(new java.awt.Color(74, 78, 77));
        jTF_6SearchBookingOptions.setBorder(null);
        jTF_6SearchBookingOptions.setMinimumSize(null);
        jTF_6SearchBookingOptions.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_7SearchBookingOptions.setEditable(false);
        jTF_7SearchBookingOptions.setBackground(new java.awt.Color(255, 255, 255));
        jTF_7SearchBookingOptions.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_7SearchBookingOptions.setForeground(new java.awt.Color(74, 78, 77));
        jTF_7SearchBookingOptions.setBorder(null);
        jTF_7SearchBookingOptions.setMinimumSize(null);
        jTF_7SearchBookingOptions.setPreferredSize(new java.awt.Dimension(64, 25));

        javax.swing.GroupLayout jP_BookingOptionsLayout = new javax.swing.GroupLayout(jP_BookingOptions);
        jP_BookingOptions.setLayout(jP_BookingOptionsLayout);
        jP_BookingOptionsLayout.setHorizontalGroup(
            jP_BookingOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BookingOptionsLayout.createSequentialGroup()
                .addGroup(jP_BookingOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_BookingOptionsLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jS_BookingOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(jP_BookingOptionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jP_BookingOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_1SearchBookingOptions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_BookingOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jP_BookingOptionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_2SearchBookingOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_BookingOptionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_3SearchBookingOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_BookingOptionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_4SearchBookingOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_BookingOptionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_5SearchBookingOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_BookingOptionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_6SearchBookingOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_BookingOptionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_7SearchBookingOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jP_BookingOptionsLayout.setVerticalGroup(
            jP_BookingOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BookingOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_BookingOptions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jS_BookingOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTF_1SearchBookingOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_2SearchBookingOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_3SearchBookingOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_4SearchBookingOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_5SearchBookingOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_6SearchBookingOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_7SearchBookingOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jP_ListOfAttractions.setBackground(new java.awt.Color(255, 255, 255));
        jP_ListOfAttractions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 78, 77)));
        jP_ListOfAttractions.setMaximumSize(new java.awt.Dimension(200, 350));

        jL_ListOfAttractions.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jL_ListOfAttractions.setForeground(new java.awt.Color(74, 78, 77));
        jL_ListOfAttractions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_ListOfAttractions.setText("List of attractions");

        jS_ListOfAttractions.setBackground(new java.awt.Color(255, 255, 255));
        jS_ListOfAttractions.setForeground(new java.awt.Color(74, 78, 77));

        jTF_1SearchListOfAttractions.setEditable(false);
        jTF_1SearchListOfAttractions.setBackground(new java.awt.Color(255, 255, 255));
        jTF_1SearchListOfAttractions.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_1SearchListOfAttractions.setForeground(new java.awt.Color(74, 78, 77));
        jTF_1SearchListOfAttractions.setBorder(null);
        jTF_1SearchListOfAttractions.setMinimumSize(new java.awt.Dimension(64, 25));
        jTF_1SearchListOfAttractions.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_2SearchListOfAttractions.setEditable(false);
        jTF_2SearchListOfAttractions.setBackground(new java.awt.Color(255, 255, 255));
        jTF_2SearchListOfAttractions.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_2SearchListOfAttractions.setForeground(new java.awt.Color(74, 78, 77));
        jTF_2SearchListOfAttractions.setBorder(null);
        jTF_2SearchListOfAttractions.setMinimumSize(new java.awt.Dimension(64, 25));
        jTF_2SearchListOfAttractions.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_3SearchListOfAttractions.setEditable(false);
        jTF_3SearchListOfAttractions.setBackground(new java.awt.Color(255, 255, 255));
        jTF_3SearchListOfAttractions.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_3SearchListOfAttractions.setForeground(new java.awt.Color(74, 78, 77));
        jTF_3SearchListOfAttractions.setBorder(null);
        jTF_3SearchListOfAttractions.setMinimumSize(new java.awt.Dimension(64, 25));
        jTF_3SearchListOfAttractions.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_4SearchListOfAttractions.setEditable(false);
        jTF_4SearchListOfAttractions.setBackground(new java.awt.Color(255, 255, 255));
        jTF_4SearchListOfAttractions.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_4SearchListOfAttractions.setForeground(new java.awt.Color(74, 78, 77));
        jTF_4SearchListOfAttractions.setBorder(null);
        jTF_4SearchListOfAttractions.setMinimumSize(new java.awt.Dimension(64, 25));
        jTF_4SearchListOfAttractions.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_5SearchListOfAttractions.setEditable(false);
        jTF_5SearchListOfAttractions.setBackground(new java.awt.Color(255, 255, 255));
        jTF_5SearchListOfAttractions.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_5SearchListOfAttractions.setForeground(new java.awt.Color(74, 78, 77));
        jTF_5SearchListOfAttractions.setBorder(null);
        jTF_5SearchListOfAttractions.setMinimumSize(new java.awt.Dimension(64, 25));
        jTF_5SearchListOfAttractions.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_6SearchListOfAttractions.setEditable(false);
        jTF_6SearchListOfAttractions.setBackground(new java.awt.Color(255, 255, 255));
        jTF_6SearchListOfAttractions.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_6SearchListOfAttractions.setForeground(new java.awt.Color(74, 78, 77));
        jTF_6SearchListOfAttractions.setBorder(null);
        jTF_6SearchListOfAttractions.setMinimumSize(new java.awt.Dimension(64, 25));
        jTF_6SearchListOfAttractions.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_7SearchListOfAttractions.setEditable(false);
        jTF_7SearchListOfAttractions.setBackground(new java.awt.Color(255, 255, 255));
        jTF_7SearchListOfAttractions.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_7SearchListOfAttractions.setForeground(new java.awt.Color(74, 78, 77));
        jTF_7SearchListOfAttractions.setBorder(null);
        jTF_7SearchListOfAttractions.setMinimumSize(new java.awt.Dimension(64, 25));
        jTF_7SearchListOfAttractions.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_8SearchListOfAttractions.setEditable(false);
        jTF_8SearchListOfAttractions.setBackground(new java.awt.Color(255, 255, 255));
        jTF_8SearchListOfAttractions.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_8SearchListOfAttractions.setForeground(new java.awt.Color(74, 78, 77));
        jTF_8SearchListOfAttractions.setBorder(null);
        jTF_8SearchListOfAttractions.setMinimumSize(new java.awt.Dimension(64, 25));
        jTF_8SearchListOfAttractions.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_9SearchListOfAttractions.setEditable(false);
        jTF_9SearchListOfAttractions.setBackground(new java.awt.Color(255, 255, 255));
        jTF_9SearchListOfAttractions.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_9SearchListOfAttractions.setForeground(new java.awt.Color(74, 78, 77));
        jTF_9SearchListOfAttractions.setBorder(null);
        jTF_9SearchListOfAttractions.setMinimumSize(new java.awt.Dimension(64, 25));
        jTF_9SearchListOfAttractions.setPreferredSize(new java.awt.Dimension(64, 25));

        javax.swing.GroupLayout jP_ListOfAttractionsLayout = new javax.swing.GroupLayout(jP_ListOfAttractions);
        jP_ListOfAttractions.setLayout(jP_ListOfAttractionsLayout);
        jP_ListOfAttractionsLayout.setHorizontalGroup(
            jP_ListOfAttractionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ListOfAttractionsLayout.createSequentialGroup()
                .addGroup(jP_ListOfAttractionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_ListOfAttractionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jL_ListOfAttractions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_ListOfAttractionsLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jS_ListOfAttractions, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(jP_ListOfAttractionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jP_ListOfAttractionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_1SearchListOfAttractions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTF_2SearchListOfAttractions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jP_ListOfAttractionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_3SearchListOfAttractions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_ListOfAttractionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_4SearchListOfAttractions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_ListOfAttractionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_5SearchListOfAttractions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_ListOfAttractionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_6SearchListOfAttractions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_ListOfAttractionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_7SearchListOfAttractions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_ListOfAttractionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_8SearchListOfAttractions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_ListOfAttractionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_9SearchListOfAttractions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jP_ListOfAttractionsLayout.setVerticalGroup(
            jP_ListOfAttractionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ListOfAttractionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_ListOfAttractions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jS_ListOfAttractions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTF_1SearchListOfAttractions, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_2SearchListOfAttractions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_3SearchListOfAttractions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_4SearchListOfAttractions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_5SearchListOfAttractions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_6SearchListOfAttractions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_7SearchListOfAttractions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_8SearchListOfAttractions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_9SearchListOfAttractions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jP_Reserved.setBackground(new java.awt.Color(255, 255, 255));
        jP_Reserved.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jL_Reserved.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jL_Reserved.setForeground(new java.awt.Color(74, 78, 77));
        jL_Reserved.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Reserved.setText("Your reservations");

        jS_Reserved.setBackground(new java.awt.Color(255, 255, 255));
        jS_Reserved.setForeground(new java.awt.Color(74, 78, 77));

        jTF_1SearchReserved.setEditable(false);
        jTF_1SearchReserved.setBackground(new java.awt.Color(255, 255, 255));
        jTF_1SearchReserved.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_1SearchReserved.setBorder(null);
        jTF_1SearchReserved.setMaximumSize(new java.awt.Dimension(64, 25));
        jTF_1SearchReserved.setMinimumSize(new java.awt.Dimension(64, 25));
        jTF_1SearchReserved.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_2SearchReserved.setEditable(false);
        jTF_2SearchReserved.setBackground(new java.awt.Color(255, 255, 255));
        jTF_2SearchReserved.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_2SearchReserved.setBorder(null);
        jTF_2SearchReserved.setMaximumSize(new java.awt.Dimension(64, 25));
        jTF_2SearchReserved.setMinimumSize(new java.awt.Dimension(64, 25));
        jTF_2SearchReserved.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_3SearchReserved.setEditable(false);
        jTF_3SearchReserved.setBackground(new java.awt.Color(255, 255, 255));
        jTF_3SearchReserved.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_3SearchReserved.setBorder(null);
        jTF_3SearchReserved.setMaximumSize(new java.awt.Dimension(64, 25));
        jTF_3SearchReserved.setMinimumSize(new java.awt.Dimension(64, 25));
        jTF_3SearchReserved.setPreferredSize(new java.awt.Dimension(64, 25));

        jTF_4SearchReserved.setEditable(false);
        jTF_4SearchReserved.setBackground(new java.awt.Color(255, 255, 255));
        jTF_4SearchReserved.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_4SearchReserved.setBorder(null);
        jTF_4SearchReserved.setMaximumSize(new java.awt.Dimension(64, 25));
        jTF_4SearchReserved.setMinimumSize(new java.awt.Dimension(64, 25));
        jTF_4SearchReserved.setPreferredSize(new java.awt.Dimension(64, 25));

        javax.swing.GroupLayout jP_ReservedLayout = new javax.swing.GroupLayout(jP_Reserved);
        jP_Reserved.setLayout(jP_ReservedLayout);
        jP_ReservedLayout.setHorizontalGroup(
            jP_ReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ReservedLayout.createSequentialGroup()
                .addGroup(jP_ReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_ReservedLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jS_Reserved, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jP_ReservedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jP_ReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_1SearchReserved, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_Reserved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jP_ReservedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_2SearchReserved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_ReservedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_3SearchReserved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_ReservedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_4SearchReserved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jP_ReservedLayout.setVerticalGroup(
            jP_ReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ReservedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_Reserved)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jS_Reserved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTF_1SearchReserved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_2SearchReserved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_3SearchReserved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_4SearchReserved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jP_Buttons.setBackground(new java.awt.Color(74, 78, 77));

        jP_Load.setBackground(new java.awt.Color(74, 78, 77));

        jComboBox1.setBackground(new java.awt.Color(74, 78, 77));
        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jComboBox1.setForeground(java.awt.Color.white);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Load" }));
        jComboBox1.setBorder(null);

        javax.swing.GroupLayout jP_LoadLayout = new javax.swing.GroupLayout(jP_Load);
        jP_Load.setLayout(jP_LoadLayout);
        jP_LoadLayout.setHorizontalGroup(
            jP_LoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_LoadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_LoadLayout.setVerticalGroup(
            jP_LoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jP_Save.setBackground(new java.awt.Color(74, 78, 77));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Save");

        javax.swing.GroupLayout jP_SaveLayout = new javax.swing.GroupLayout(jP_Save);
        jP_Save.setLayout(jP_SaveLayout);
        jP_SaveLayout.setHorizontalGroup(
            jP_SaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_SaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_SaveLayout.setVerticalGroup(
            jP_SaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        jL_Line.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jL_Line.setForeground(java.awt.Color.white);
        jL_Line.setText("|");

        javax.swing.GroupLayout jP_ButtonsLayout = new javax.swing.GroupLayout(jP_Buttons);
        jP_Buttons.setLayout(jP_ButtonsLayout);
        jP_ButtonsLayout.setHorizontalGroup(
            jP_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_Save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_Line)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP_Load, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_ButtonsLayout.setVerticalGroup(
            jP_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_ButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jP_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jL_Line, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jP_Load, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_Save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        jP_JourneyPlan.setBackground(new java.awt.Color(255, 255, 255));
        jP_JourneyPlan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 78, 77)));

        jSP_JourneyPlan.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        jSP_JourneyPlan.setForeground(new java.awt.Color(74, 78, 77));
        jSP_JourneyPlan.setToolTipText("");

        jTA_JourneyPlan.setColumns(20);
        jTA_JourneyPlan.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTA_JourneyPlan.setForeground(new java.awt.Color(74, 78, 77));
        jTA_JourneyPlan.setRows(5);
        jTA_JourneyPlan.setText("1. Sleep\n2. Eat\n3. Sleep");
        jSP_JourneyPlan.setViewportView(jTA_JourneyPlan);

        jL_JourneyPlan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jL_JourneyPlan.setForeground(new java.awt.Color(74, 78, 77));
        jL_JourneyPlan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_JourneyPlan.setText("Journey Plan");

        jS_JourneyPlan.setForeground(new java.awt.Color(74, 78, 77));

        javax.swing.GroupLayout jP_JourneyPlanLayout = new javax.swing.GroupLayout(jP_JourneyPlan);
        jP_JourneyPlan.setLayout(jP_JourneyPlanLayout);
        jP_JourneyPlanLayout.setHorizontalGroup(
            jP_JourneyPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_JourneyPlanLayout.createSequentialGroup()
                .addGroup(jP_JourneyPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_JourneyPlanLayout.createSequentialGroup()
                        .addGroup(jP_JourneyPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_JourneyPlanLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jL_JourneyPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jP_JourneyPlanLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jS_JourneyPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(jP_JourneyPlanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSP_JourneyPlan)))
                .addContainerGap())
        );
        jP_JourneyPlanLayout.setVerticalGroup(
            jP_JourneyPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_JourneyPlanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_JourneyPlan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jS_JourneyPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSP_JourneyPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTF_Search.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTF_Search.setForeground(new java.awt.Color(74, 78, 77));
        jTF_Search.setText(" Search for a city...");
        jTF_Search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 78, 77)));

        javax.swing.GroupLayout jP_ContentsLayout = new javax.swing.GroupLayout(jP_Contents);
        jP_Contents.setLayout(jP_ContentsLayout);
        jP_ContentsLayout.setHorizontalGroup(
            jP_ContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_ContentsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jP_ContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jP_ListOfAttractions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_Reserved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jP_ContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_Buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_JourneyPlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTF_Search))
                .addGap(18, 18, 18)
                .addGroup(jP_ContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jP_BookingOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_Accommodation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jP_ContentsLayout.setVerticalGroup(
            jP_ContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ContentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_ContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jP_ContentsLayout.createSequentialGroup()
                        .addComponent(jP_Accommodation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jP_BookingOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_ContentsLayout.createSequentialGroup()
                        .addComponent(jP_ListOfAttractions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jP_Reserved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_ContentsLayout.createSequentialGroup()
                        .addComponent(jTF_Search)
                        .addGap(18, 18, 18)
                        .addComponent(jP_Buttons, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jP_JourneyPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jP_ContainerLayout = new javax.swing.GroupLayout(jP_Container);
        jP_Container.setLayout(jP_ContainerLayout);
        jP_ContainerLayout.setHorizontalGroup(
            jP_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_TopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jP_Contents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jP_ContainerLayout.setVerticalGroup(
            jP_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ContainerLayout.createSequentialGroup()
                .addComponent(jP_TopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP_Contents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        String[] Citiees = {"Warszawa", "Kraków", "Zielona Góra", "Poznań", "Częstochowa"};
        
        static String NotFound = "Not Found... :(";
        jTF_1SearchAccommodation.setText
        
        Cities cities = new Cities();
        
        int CL = Citiees.length; //CL - Cities Length
        
        for (int i=0;i<CL;i++) {
            if (i == 0) {
                String city = Citiees[i];
                
                if (i == 0) {
                    jTF_1SearchAccommodation.setText(city);
                }
            }
        }
       
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jL_Accommodation;
    private javax.swing.JLabel jL_BookingOptions;
    private javax.swing.JLabel jL_Exit;
    private javax.swing.JLabel jL_JourneyPlan;
    private javax.swing.JLabel jL_Line;
    private javax.swing.JLabel jL_ListOfAttractions;
    private javax.swing.JLabel jL_Minimize;
    private javax.swing.JLabel jL_NameOfAplicationFirstPart;
    private javax.swing.JLabel jL_NameOfAplicationSecondPart;
    private javax.swing.JLabel jL_Reserved;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jP_Accommodation;
    private javax.swing.JPanel jP_BookingOptions;
    private javax.swing.JPanel jP_Buttons;
    private javax.swing.JPanel jP_Container;
    private javax.swing.JPanel jP_Contents;
    private javax.swing.JPanel jP_JourneyPlan;
    private javax.swing.JPanel jP_ListOfAttractions;
    private javax.swing.JPanel jP_Load;
    private javax.swing.JPanel jP_Reserved;
    private javax.swing.JPanel jP_Save;
    private javax.swing.JPanel jP_TopBar;
    private javax.swing.JScrollPane jSP_JourneyPlan;
    private javax.swing.JSeparator jS_Accommodation;
    private javax.swing.JSeparator jS_BookingOptions;
    private javax.swing.JSeparator jS_JourneyPlan;
    private javax.swing.JSeparator jS_ListOfAttractions;
    private javax.swing.JSeparator jS_Reserved;
    private javax.swing.JTextArea jTA_JourneyPlan;
    private javax.swing.JTextField jTF_1SearchAccommodation;
    private javax.swing.JTextField jTF_1SearchBookingOptions;
    private javax.swing.JTextField jTF_1SearchListOfAttractions;
    private javax.swing.JTextField jTF_1SearchReserved;
    private javax.swing.JTextField jTF_2SearchAccommodation;
    private javax.swing.JTextField jTF_2SearchBookingOptions;
    private javax.swing.JTextField jTF_2SearchListOfAttractions;
    private javax.swing.JTextField jTF_2SearchReserved;
    private javax.swing.JTextField jTF_3SearchAccommodation;
    private javax.swing.JTextField jTF_3SearchBookingOptions;
    private javax.swing.JTextField jTF_3SearchListOfAttractions;
    private javax.swing.JTextField jTF_3SearchReserved;
    private javax.swing.JTextField jTF_4SearchAccommodation;
    private javax.swing.JTextField jTF_4SearchBookingOptions;
    private javax.swing.JTextField jTF_4SearchListOfAttractions;
    private javax.swing.JTextField jTF_4SearchReserved;
    private javax.swing.JTextField jTF_5SearchAccommodation;
    private javax.swing.JTextField jTF_5SearchBookingOptions;
    private javax.swing.JTextField jTF_5SearchListOfAttractions;
    private javax.swing.JTextField jTF_6SearchBookingOptions;
    private javax.swing.JTextField jTF_6SearchListOfAttractions;
    private javax.swing.JTextField jTF_7SearchBookingOptions;
    private javax.swing.JTextField jTF_7SearchListOfAttractions;
    private javax.swing.JTextField jTF_8SearchListOfAttractions;
    private javax.swing.JTextField jTF_9SearchListOfAttractions;
    private javax.swing.JTextField jTF_Search;
    // End of variables declaration//GEN-END:variables
}
