/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author musialantoni
 */
public class RGB_color_changer extends javax.swing.JFrame {

    /**
     * Creates new form RGB_color_changer
     */
    public RGB_color_changer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_Everything = new javax.swing.JPanel();
        jP_RED_Slider = new javax.swing.JPanel();
        jL_RED_Slider = new javax.swing.JLabel();
        jS_RED_Slider = new javax.swing.JSlider();
        jP_GREEN_Slider = new javax.swing.JPanel();
        jL_GREEN_Slider = new javax.swing.JLabel();
        jS_GREEN_Slider = new javax.swing.JSlider();
        jP_BLUE_Slider = new javax.swing.JPanel();
        jL_BLUE_Slider = new javax.swing.JLabel();
        jS_BLUE_Slider = new javax.swing.JSlider();
        jP_Properties_from_sliders = new javax.swing.JPanel();
        jP_RED_Properties_from_slider = new javax.swing.JPanel();
        jL_RED_Properties_from_slider = new javax.swing.JLabel();
        jL_RED_Properties_from_slider_value = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jP_GREEN_Properties_from_slider = new javax.swing.JPanel();
        jL_GREEN_Properties_from_slider = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jL_GREEN_Properties_from_slider_value = new javax.swing.JLabel();
        jP_BLUE_Properties_from_slider = new javax.swing.JPanel();
        jL_BLUE_Properties_from_slider = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jL_BLUE_Properties_from_slider_value = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jP_Everything.setBackground(java.awt.Color.darkGray);

        jP_RED_Slider.setBackground(java.awt.Color.gray);

        jL_RED_Slider.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jL_RED_Slider.setForeground(java.awt.Color.white);
        jL_RED_Slider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_RED_Slider.setText("Red");

        jS_RED_Slider.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jS_RED_Slider.setForeground(java.awt.Color.white);
        jS_RED_Slider.setMajorTickSpacing(25);
        jS_RED_Slider.setMaximum(255);
        jS_RED_Slider.setMinorTickSpacing(1);
        jS_RED_Slider.setPaintLabels(true);
        jS_RED_Slider.setSnapToTicks(true);
        jS_RED_Slider.setValue(100);

        javax.swing.GroupLayout jP_RED_SliderLayout = new javax.swing.GroupLayout(jP_RED_Slider);
        jP_RED_Slider.setLayout(jP_RED_SliderLayout);
        jP_RED_SliderLayout.setHorizontalGroup(
            jP_RED_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_RED_SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_RED_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jS_RED_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_RED_SliderLayout.setVerticalGroup(
            jP_RED_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_RED_SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_RED_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_RED_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jS_RED_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jP_GREEN_Slider.setBackground(java.awt.Color.gray);

        jL_GREEN_Slider.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jL_GREEN_Slider.setForeground(java.awt.Color.white);
        jL_GREEN_Slider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_GREEN_Slider.setText("Green");

        jS_GREEN_Slider.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jS_GREEN_Slider.setForeground(java.awt.Color.white);
        jS_GREEN_Slider.setMajorTickSpacing(25);
        jS_GREEN_Slider.setMaximum(255);
        jS_GREEN_Slider.setMinorTickSpacing(1);
        jS_GREEN_Slider.setPaintLabels(true);
        jS_GREEN_Slider.setSnapToTicks(true);
        jS_GREEN_Slider.setValue(100);

        javax.swing.GroupLayout jP_GREEN_SliderLayout = new javax.swing.GroupLayout(jP_GREEN_Slider);
        jP_GREEN_Slider.setLayout(jP_GREEN_SliderLayout);
        jP_GREEN_SliderLayout.setHorizontalGroup(
            jP_GREEN_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_GREEN_SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_GREEN_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jS_GREEN_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_GREEN_SliderLayout.setVerticalGroup(
            jP_GREEN_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_GREEN_SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_GREEN_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_GREEN_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jS_GREEN_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jP_BLUE_Slider.setBackground(java.awt.Color.gray);

        jL_BLUE_Slider.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jL_BLUE_Slider.setForeground(java.awt.Color.white);
        jL_BLUE_Slider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_BLUE_Slider.setText("Blue");

        jS_BLUE_Slider.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jS_BLUE_Slider.setForeground(java.awt.Color.white);
        jS_BLUE_Slider.setMajorTickSpacing(25);
        jS_BLUE_Slider.setMaximum(255);
        jS_BLUE_Slider.setMinorTickSpacing(1);
        jS_BLUE_Slider.setPaintLabels(true);
        jS_BLUE_Slider.setSnapToTicks(true);
        jS_BLUE_Slider.setValue(100);

        javax.swing.GroupLayout jP_BLUE_SliderLayout = new javax.swing.GroupLayout(jP_BLUE_Slider);
        jP_BLUE_Slider.setLayout(jP_BLUE_SliderLayout);
        jP_BLUE_SliderLayout.setHorizontalGroup(
            jP_BLUE_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BLUE_SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_BLUE_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jS_BLUE_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_BLUE_SliderLayout.setVerticalGroup(
            jP_BLUE_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BLUE_SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_BLUE_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_BLUE_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jS_BLUE_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        jP_Properties_from_sliders.setBackground(java.awt.Color.gray);

        jP_RED_Properties_from_slider.setBackground(java.awt.Color.lightGray);

        jL_RED_Properties_from_slider.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jL_RED_Properties_from_slider.setForeground(java.awt.Color.red);
        jL_RED_Properties_from_slider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_RED_Properties_from_slider.setText("RED");

        jL_RED_Properties_from_slider_value.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jL_RED_Properties_from_slider_value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_RED_Properties_from_slider_value.setText("100");

        jSeparator1.setForeground(java.awt.Color.black);

        javax.swing.GroupLayout jP_RED_Properties_from_sliderLayout = new javax.swing.GroupLayout(jP_RED_Properties_from_slider);
        jP_RED_Properties_from_slider.setLayout(jP_RED_Properties_from_sliderLayout);
        jP_RED_Properties_from_sliderLayout.setHorizontalGroup(
            jP_RED_Properties_from_sliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_RED_Properties_from_sliderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_RED_Properties_from_sliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jL_RED_Properties_from_slider, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jL_RED_Properties_from_slider_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jP_RED_Properties_from_sliderLayout.setVerticalGroup(
            jP_RED_Properties_from_sliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_RED_Properties_from_sliderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_RED_Properties_from_slider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_RED_Properties_from_slider_value)
                .addContainerGap())
        );

        jP_GREEN_Properties_from_slider.setBackground(java.awt.Color.lightGray);

        jL_GREEN_Properties_from_slider.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jL_GREEN_Properties_from_slider.setForeground(java.awt.Color.green);
        jL_GREEN_Properties_from_slider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_GREEN_Properties_from_slider.setText("Green");

        jSeparator2.setForeground(java.awt.Color.black);

        jL_GREEN_Properties_from_slider_value.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jL_GREEN_Properties_from_slider_value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_GREEN_Properties_from_slider_value.setText("100");

        javax.swing.GroupLayout jP_GREEN_Properties_from_sliderLayout = new javax.swing.GroupLayout(jP_GREEN_Properties_from_slider);
        jP_GREEN_Properties_from_slider.setLayout(jP_GREEN_Properties_from_sliderLayout);
        jP_GREEN_Properties_from_sliderLayout.setHorizontalGroup(
            jP_GREEN_Properties_from_sliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_GREEN_Properties_from_sliderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_GREEN_Properties_from_sliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_GREEN_Properties_from_slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL_GREEN_Properties_from_slider_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jP_GREEN_Properties_from_sliderLayout.setVerticalGroup(
            jP_GREEN_Properties_from_sliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_GREEN_Properties_from_sliderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_GREEN_Properties_from_slider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_GREEN_Properties_from_slider_value)
                .addContainerGap())
        );

        jP_BLUE_Properties_from_slider.setBackground(java.awt.Color.lightGray);

        jL_BLUE_Properties_from_slider.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jL_BLUE_Properties_from_slider.setForeground(java.awt.Color.blue);
        jL_BLUE_Properties_from_slider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_BLUE_Properties_from_slider.setText("BLUE");

        jSeparator3.setForeground(java.awt.Color.black);

        jL_BLUE_Properties_from_slider_value.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jL_BLUE_Properties_from_slider_value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_BLUE_Properties_from_slider_value.setText("100");

        javax.swing.GroupLayout jP_BLUE_Properties_from_sliderLayout = new javax.swing.GroupLayout(jP_BLUE_Properties_from_slider);
        jP_BLUE_Properties_from_slider.setLayout(jP_BLUE_Properties_from_sliderLayout);
        jP_BLUE_Properties_from_sliderLayout.setHorizontalGroup(
            jP_BLUE_Properties_from_sliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BLUE_Properties_from_sliderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_BLUE_Properties_from_sliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator3)
                    .addComponent(jL_BLUE_Properties_from_slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL_BLUE_Properties_from_slider_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_BLUE_Properties_from_sliderLayout.setVerticalGroup(
            jP_BLUE_Properties_from_sliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BLUE_Properties_from_sliderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_BLUE_Properties_from_slider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_BLUE_Properties_from_slider_value)
                .addContainerGap())
        );

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(java.awt.Color.lightGray);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HTML");

        jSeparator4.setForeground(java.awt.Color.black);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("#ffffff");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jP_Properties_from_slidersLayout = new javax.swing.GroupLayout(jP_Properties_from_sliders);
        jP_Properties_from_sliders.setLayout(jP_Properties_from_slidersLayout);
        jP_Properties_from_slidersLayout.setHorizontalGroup(
            jP_Properties_from_slidersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_Properties_from_slidersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_RED_Properties_from_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jP_GREEN_Properties_from_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jP_BLUE_Properties_from_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jP_Properties_from_slidersLayout.setVerticalGroup(
            jP_Properties_from_slidersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_Properties_from_slidersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_Properties_from_slidersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_BLUE_Properties_from_slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_GREEN_Properties_from_slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_RED_Properties_from_slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_Properties_from_slidersLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jP_EverythingLayout = new javax.swing.GroupLayout(jP_Everything);
        jP_Everything.setLayout(jP_EverythingLayout);
        jP_EverythingLayout.setHorizontalGroup(
            jP_EverythingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_EverythingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_EverythingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jP_BLUE_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_GREEN_Slider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_RED_Slider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_EverythingLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jP_Properties_from_sliders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        jP_EverythingLayout.setVerticalGroup(
            jP_EverythingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_EverythingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_RED_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jP_GREEN_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jP_BLUE_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jP_Properties_from_sliders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Everything, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Everything, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RGB_color_changer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RGB_color_changer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RGB_color_changer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RGB_color_changer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RGB_color_changer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_BLUE_Properties_from_slider;
    private javax.swing.JLabel jL_BLUE_Properties_from_slider_value;
    private javax.swing.JLabel jL_BLUE_Slider;
    private javax.swing.JLabel jL_GREEN_Properties_from_slider;
    private javax.swing.JLabel jL_GREEN_Properties_from_slider_value;
    private javax.swing.JLabel jL_GREEN_Slider;
    private javax.swing.JLabel jL_RED_Properties_from_slider;
    private javax.swing.JLabel jL_RED_Properties_from_slider_value;
    private javax.swing.JLabel jL_RED_Slider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jP_BLUE_Properties_from_slider;
    private javax.swing.JPanel jP_BLUE_Slider;
    private javax.swing.JPanel jP_Everything;
    private javax.swing.JPanel jP_GREEN_Properties_from_slider;
    private javax.swing.JPanel jP_GREEN_Slider;
    private javax.swing.JPanel jP_Properties_from_sliders;
    private javax.swing.JPanel jP_RED_Properties_from_slider;
    private javax.swing.JPanel jP_RED_Slider;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider jS_BLUE_Slider;
    private javax.swing.JSlider jS_GREEN_Slider;
    private javax.swing.JSlider jS_RED_Slider;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
