/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mnemonics;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author musialantoni
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOP_About = new javax.swing.JOptionPane();
        jP_Container = new javax.swing.JPanel();
        jSP = new javax.swing.JScrollPane();
        jTA_Thoughts = new javax.swing.JTextArea();
        jMB = new javax.swing.JMenuBar();
        jM_File = new javax.swing.JMenu();
        jMI_NetThoughts = new javax.swing.JMenuItem();
        jMI_Save = new javax.swing.JMenuItem();
        jMI_Exit = new javax.swing.JMenuItem();
        jM_Edit = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thoughts");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jSP.setToolTipText("");
        jSP.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N

        jTA_Thoughts.setColumns(20);
        jTA_Thoughts.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 14)); // NOI18N
        jTA_Thoughts.setRows(5);
        jSP.setViewportView(jTA_Thoughts);

        javax.swing.GroupLayout jP_ContainerLayout = new javax.swing.GroupLayout(jP_Container);
        jP_Container.setLayout(jP_ContainerLayout);
        jP_ContainerLayout.setHorizontalGroup(
            jP_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSP, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_ContainerLayout.setVerticalGroup(
            jP_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSP, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        jM_File.setText("File");
        jM_File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_FileActionPerformed(evt);
            }
        });

        jMI_NetThoughts.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMI_NetThoughts.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        jMI_NetThoughts.setText("New thoughts");
        jMI_NetThoughts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_NetThoughtsActionPerformed(evt);
            }
        });
        jM_File.add(jMI_NetThoughts);

        jMI_Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMI_Save.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        jMI_Save.setText("Save");
        jMI_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_SaveActionPerformed(evt);
            }
        });
        jM_File.add(jMI_Save);

        jMI_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMI_Exit.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        jMI_Exit.setText("Exit");
        jMI_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_ExitActionPerformed(evt);
            }
        });
        jM_File.add(jMI_Exit);

        jMB.add(jM_File);

        jM_Edit.setText("Edit");

        jMenuItem4.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        jMenuItem4.setText("Help");
        jM_Edit.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem5.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        jMenuItem5.setText("About");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jM_Edit.add(jMenuItem5);

        jMB.add(jM_Edit);

        setJMenuBar(jMB);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jM_FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_FileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jM_FileActionPerformed

    private void jMI_NetThoughtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_NetThoughtsActionPerformed
        // TODO add your handling code here:
        jTA_Thoughts.setText("");
    }//GEN-LAST:event_jMI_NetThoughtsActionPerformed

    private void jMI_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_SaveActionPerformed
        // TODO add your handling code here:
        String thoughts = jTA_Thoughts.getText();
        System.out.println(thoughts);
        
        FileReader reader = null;
        try {
            reader = new FileReader("/home/musialantoni/Desktop/GitHub/Antoni_musial_repo_desktopowe/3 PTN/II Semestr/mnemonic/mnemonics/src/main/java/com/mycompany/mnemonics/thoughts.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String content = "";
        int i;
        try {
            while((i=reader.read()) !=-1) {
                content += (char) i;
            }
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            reader.close();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        content += "Nowytekst";
        
        try {
            FileWriter writer = new FileWriter("/home/musialantoni/Desktop/GitHub/Antoni_musial_repo_desktopowe/3 PTN/II Semestr/mnemonic/mnemonics/src/main/java/com/mycompany/mnemonics/thoughts.txt", true);
            writer.write(thoughts + "\n");
            writer.close();
            jTA_Thoughts.setText(thoughts + "\nSaved");
        } catch (Exception e) {
            jTA_Thoughts.setText(thoughts + "\nError");
        }
    }//GEN-LAST:event_jMI_SaveActionPerformed

    private void jMI_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMI_ExitActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jOP_About.setVisible(true);
        
        String about =  "<html><body>" +
                        "<h1>O programie</h1>" +
                        "<p>Program zbierający myśli<br> Autor: Antoni Musiał</p>" +
                        "</body></html>";
        
        jOP_About.showMessageDialog(null, about, "About", jOP_About.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        System.out.print("s");
        
        File file = new File("/home/musialantoni/Desktop/GitHub/Antoni_musial_repo_desktopowe/3 PTN/II Semestr/mnemonic/mnemonics/src/main/java/com/mycompany/mnemonics/thoughts.txt");
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String LastThought = "";
            String line;
            while ((line = br.readLine()) != null) {
                LastThought = line;
            }
            br.close();
            System.out.println(LastThought);
            jTA_Thoughts.setText(LastThought);
        } catch (IOException e) {
            System.out.println("Błąd odczytu pliku");
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMB;
    private javax.swing.JMenuItem jMI_Exit;
    private javax.swing.JMenuItem jMI_NetThoughts;
    private javax.swing.JMenuItem jMI_Save;
    private javax.swing.JMenu jM_Edit;
    private javax.swing.JMenu jM_File;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JOptionPane jOP_About;
    private javax.swing.JPanel jP_Container;
    private javax.swing.JScrollPane jSP;
    private javax.swing.JTextArea jTA_Thoughts;
    // End of variables declaration//GEN-END:variables
}
