/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chej_antivirus;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author monst
 */
public class Chej_AntiVirus extends javax.swing.JFrame {

    /**
     * Creates new form Chej_AntiVirus
     */
    public Chej_AntiVirus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPAll = new javax.swing.JPanel();
        jPLoading_screen = new javax.swing.JPanel();
        jLLoading_gif = new javax.swing.JLabel();
        jPProgress = new javax.swing.JPanel();
        jPBLoading = new javax.swing.JProgressBar();
        jLProcents = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(480, 290));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(480, 290));
        setResizable(false);
        setSize(new java.awt.Dimension(480, 280));

        jPAll.setBackground(new java.awt.Color(43, 48, 134));
        jPAll.setMaximumSize(new java.awt.Dimension(480, 280));
        jPAll.setPreferredSize(new java.awt.Dimension(480, 280));

        jPLoading_screen.setMaximumSize(new java.awt.Dimension(480, 270));
        jPLoading_screen.setPreferredSize(new java.awt.Dimension(480, 270));

        javax.swing.GroupLayout jPLoading_screenLayout = new javax.swing.GroupLayout(jPLoading_screen);
        jPLoading_screen.setLayout(jPLoading_screenLayout);
        jPLoading_screenLayout.setHorizontalGroup(
            jPLoading_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLLoading_gif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPLoading_screenLayout.setVerticalGroup(
            jPLoading_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoading_screenLayout.createSequentialGroup()
                .addComponent(jLLoading_gif, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPProgress.setBackground(java.awt.Color.darkGray);
        jPProgress.setMaximumSize(new java.awt.Dimension(480, 20));
        jPProgress.setMinimumSize(new java.awt.Dimension(100, 1));

        jPBLoading.setBackground(java.awt.Color.darkGray);
        jPBLoading.setForeground(new java.awt.Color(0, 255, 153));
        jPBLoading.setBorder(null);
        jPBLoading.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPBLoading.setPreferredSize(new java.awt.Dimension(450, 12));

        jLProcents.setFont(new java.awt.Font("Segoe UI Black", 0, 8)); // NOI18N
        jLProcents.setForeground(java.awt.Color.white);
        jLProcents.setText("0%");
        jLProcents.setMinimumSize(new java.awt.Dimension(12, 1));

        javax.swing.GroupLayout jPProgressLayout = new javax.swing.GroupLayout(jPProgress);
        jPProgress.setLayout(jPProgressLayout);
        jPProgressLayout.setHorizontalGroup(
            jPProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProgressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLProcents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPBLoading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPProgressLayout.setVerticalGroup(
            jPProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProgressLayout.createSequentialGroup()
                .addComponent(jLProcents, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPBLoading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPAllLayout = new javax.swing.GroupLayout(jPAll);
        jPAll.setLayout(jPAllLayout);
        jPAllLayout.setHorizontalGroup(
            jPAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPLoading_screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPProgress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPAllLayout.setVerticalGroup(
            jPAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAllLayout.createSequentialGroup()
                .addComponent(jPLoading_screen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPAll, javax.swing.GroupLayout.PREFERRED_SIZE, 296, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chej_AntiVirus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chej_AntiVirus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chej_AntiVirus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chej_AntiVirus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        Chej_AntiVirus chej = new Chej_AntiVirus();
        chej.setVisible(true);
        
        Chej_AntiVirus_2 chejj = new Chej_AntiVirus_2();
        for (int i = 0; i < 100; i++) {
            Thread.sleep(40);
            chej.jPBLoading.setValue(i);
            chej.jLProcents.setText(Integer.toString(i)+"%");
        }
        
        chej.setVisible(false);
        chejj.setVisible(true);
        
        chej.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLLoading_gif;
    private javax.swing.JLabel jLProcents;
    private javax.swing.JPanel jPAll;
    private javax.swing.JProgressBar jPBLoading;
    private javax.swing.JPanel jPLoading_screen;
    private javax.swing.JPanel jPProgress;
    // End of variables declaration//GEN-END:variables
}
